import Link from "next/link"
import type { LegalSection } from "@/app/components/LegalDocumentLayout"
import { SUPPORT_EMAIL } from "@/lib/contactEmails"
import { LEGAL_ENTITY_NAME } from "@/lib/legal/contact"
import { SITE_URL } from "@/lib/site"

export const PRIVACY_POLICY_SECTIONS: LegalSection[] = [
  {
    id: "introduction",
    title: "Introduction",
    content: (
      <>
        <p>
          {LEGAL_ENTITY_NAME}{" "}
          (&quot;TradeTraxs,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates a
          trading journal and social trading platform at{" "}
          <a href={SITE_URL}>{SITE_URL}</a>. This Privacy Policy explains how we collect, use,
          disclose, and protect information when you use our website, applications, and related
          services (collectively, the &quot;Service&quot;).
        </p>
        <p>
          TradeTraxs is <strong>not a broker</strong>, does not execute trades, and does not
          provide investment, financial, tax, or legal advice. By using the Service, you agree to
          this Privacy Policy. If you do not agree, please do not use the Service.
        </p>
      </>
    ),
  },
  {
    id: "beta-program",
    title: "Beta Program",
    content: (
      <>
        <p>
          TradeTraxs is currently offered as a <strong>beta product</strong>.
        </p>
        <p>
          Features, functionality, pricing, analytics, AI outputs, integrations, and availability
          may change, be modified, or be removed at any time.
        </p>
        <p>
          You acknowledge that beta software may contain bugs, inaccuracies, interruptions, or
          unexpected behavior. You should independently verify any information generated by the
          platform before relying on it.
        </p>
      </>
    ),
  },
  {
    id: "data-we-collect",
    title: "Information We Collect",
    content: (
      <>
        <p>We collect information in the following categories:</p>
        <ul>
          <li>
            <strong>Account information</strong>, email address, password (stored in hashed form
            by our authentication provider), username, display name, profile details, avatar,
            privacy settings, subscription status, and referral or affiliate identifiers you
            provide or that are assigned to you.
          </li>
          <li>
            <strong>Trading data</strong>, trades you log or import (including tickers, dates,
            profit and loss, direction, session, strategy notes, account labels, screenshots, and
            CSV import files), dashboard preferences, and analytics derived from your trading
            activity within the Service.
          </li>
          <li>
            <strong>User-generated content</strong>, posts, comments, likes, messages, Trade Room
            messages, stories, achievements, support tickets, feedback, bug reports, and any
            content you choose to make public or share with other users.
          </li>
          <li>
            <strong>Social and community data</strong>, followers, follow requests, room
            memberships, invites, notifications, and interaction history with other users.
          </li>
          <li>
            <strong>Payment information</strong>, subscription and billing metadata processed by
            Stripe (such as customer ID, plan, payment status, and transaction records). We do not
            store full payment card numbers on our servers.
          </li>
          <li>
            <strong>Technical and usage data</strong>, IP address, browser type, device
            information, log data, pages viewed, feature usage, performance metrics, and similar
            diagnostic information collected through hosting and analytics tools.
          </li>
          <li>
            <strong>Communications</strong>, messages you send to us (support, feedback, legal
            inquiries) and related metadata.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "account-information",
    title: "Account Information",
    content: (
      <>
        <p>
          When you create an account, we collect the information needed to authenticate you and
          operate your profile. You may sign up with email and password or, where enabled, third-party
          sign-in such as Google.
        </p>
        <p>
          You control certain profile settings, including whether your profile is public or private.
          Private profiles limit visibility of your trading activity and posts to approved
          followers as described in the Service. You are responsible for keeping your login
          credentials confidential.
        </p>
      </>
    ),
  },
  {
    id: "trading-data",
    title: "Trading Data",
    content: (
      <>
        <p>
          TradeTraxs is designed for journaling, performance tracking, and community sharing. You
          may enter trades manually, upload CSV files from other platforms, attach screenshots, and
          choose whether individual trades or posts are public or private.
        </p>
        <p>
          Unless you share content publicly or with other users through the Service, your private
          trade notes and non-public trades are intended to remain visible only to you and our
          systems as needed to provide the Service. We use commercially reasonable safeguards, but
          no system is perfectly secure; you should not treat the Service as a guaranteed private
          vault. CSV files you upload may be stored to complete import and, if you submit them for
          format support, to improve import compatibility.
        </p>
        <p>
          <strong>Important:</strong> Do not upload credentials, account passwords, or sensitive
          broker login information. TradeTraxs does not need broker passwords to operate.
        </p>
      </>
    ),
  },
  {
    id: "user-generated-content",
    title: "User-Generated Content",
    content: (
      <>
        <p>
          Content you publish, including feed posts, trade shares, comments, profile posts,
          messages, and Trade Room participation, may be visible to other users according to your
          settings and the feature you use.
        </p>
        <p>
          Public content may be displayed on leaderboards, explore pages, or other public areas of
          the Service according to product features and your settings. You may delete or edit
          certain content where the Service provides those controls, but copies or references may
          persist in backups, logs, or other users&apos; devices for a period of time.
        </p>
      </>
    ),
  },
  {
    id: "analytics",
    title: "Analytics and Performance Monitoring",
    content: (
      <>
        <p>We use analytics and performance tools to understand how the Service is used and to improve reliability, including:</p>
        <ul>
          <li>
            <strong>Vercel Analytics</strong>, aggregated usage and traffic metrics.
          </li>
          <li>
            <strong>Vercel Speed Insights</strong>, performance and Core Web Vitals data.
          </li>
          <li>
            <strong>Server and application logs</strong>, error reporting, security monitoring, and
            operational diagnostics through our hosting infrastructure.
          </li>
        </ul>
        <p>
          These tools may collect pseudonymous identifiers, page views, referrers, device/browser
          characteristics, and performance timings. We use this data in aggregate to improve the
          Service, not to sell your personal trading journal as a standalone product.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    title: "Cookies and Similar Technologies",
    content: (
      <>
        <p>
          We use cookies, local storage, and similar technologies to keep you signed in, remember
          preferences, protect against abuse, and measure site performance.
        </p>
        <ul>
          <li>
            <strong>Essential cookies/storage</strong>, required for authentication, security, and
            core functionality (including Supabase session management).
          </li>
          <li>
            <strong>Analytics cookies/scripts</strong>, used by Vercel Analytics and Speed Insights
            as described above.
          </li>
        </ul>
        <p>
          You can control cookies through your browser settings. Disabling essential cookies may
          prevent you from using parts of the Service.
        </p>
      </>
    ),
  },
  {
    id: "third-parties",
    title: "Third-Party Services",
    content: (
      <>
        <p>
          We rely on trusted service providers to operate TradeTraxs. They process data on our
          behalf according to their terms and our instructions. Key providers include:
        </p>
        <ul>
          <li>
            <strong>Supabase</strong>, authentication, database, storage, and backend
            infrastructure.
          </li>
          <li>
            <strong>Stripe</strong>, subscription billing and affiliate/payout processing where
            applicable.
          </li>
          <li>
            <strong>Vercel</strong>, hosting, deployment, analytics, and speed insights.
          </li>
          <li>
            <strong>Google</strong>, optional sign-in (Google OAuth) and Google Workspace for
            business email and operations.
          </li>
          <li>
            <strong>AI service providers</strong>, when you use AI Analyst, trade context
            you submit may be processed by third-party AI providers, including OpenAI where
            applicable, to generate responses. AI output may be inaccurate, incomplete, delayed, or
            incorrect and is for educational purposes only, not financial advice. Do not submit
            information you do not want processed for that purpose.
          </li>
        </ul>
        <p>
          These providers may process data in the United States and other countries. Their privacy
          policies govern their direct collection where applicable.
        </p>
      </>
    ),
  },
  {
    id: "how-we-use",
    title: "How We Use Information",
    content: (
      <>
        <p>We use collected information to:</p>
        <ul>
          <li>Provide, maintain, and improve the Service;</li>
          <li>Authenticate users and secure accounts;</li>
          <li>Process subscriptions, referrals, and affiliate payouts;</li>
          <li>Enable social features, messaging, notifications, and Trade Rooms;</li>
          <li>Generate AI-assisted trade analysis when you request it;</li>
          <li>Respond to support, feedback, and legal requests;</li>
          <li>Detect abuse, fraud, and violations of our Terms;</li>
          <li>Comply with legal obligations; and</li>
          <li>Send service-related communications (you may opt out of non-essential marketing where offered).</li>
        </ul>
      </>
    ),
  },
  {
    id: "sharing",
    title: "How We Share Information",
    content: (
      <>
        <p>We may share information:</p>
        <ul>
          <li>
            <strong>With other users</strong>, according to your sharing settings and public profile
            choices.
          </li>
          <li>
            <strong>With service providers</strong>, listed under Third-Party Services.
          </li>
          <li>
            <strong>For legal reasons</strong>, if required by law, subpoena, or to protect rights,
            safety, and integrity of the Service.
          </li>
          <li>
            <strong>Business transfers</strong>, in connection with a merger, acquisition, or sale
            of assets, subject to continued protection consistent with this policy.
          </li>
        </ul>
        <p>We do not sell your personal information for money.</p>
      </>
    ),
  },
  {
    id: "retention",
    title: "Data Retention",
    content: (
      <>
        <p>
          We retain information for as long as your account is active or as needed to provide the
          Service, comply with legal obligations, resolve disputes, and enforce our agreements.
        </p>
        <p>
          When you delete your account (where available), we will delete or anonymize personal
          information within a reasonable period, except where retention is required by law or
          legitimate business needs (such as billing records, abuse prevention, or backup systems
          that purge on a rolling schedule).
        </p>
      </>
    ),
  },
  {
    id: "security",
    title: "Security",
    content: (
      <>
        <p>
          We implement commercially reasonable administrative, technical, and organizational
          measures designed to protect information, including encryption in transit (HTTPS), access
          controls, and authentication practices through Supabase.
        </p>
        <p>
          No method of transmission or storage is completely secure. You use the Service at your own
          risk and should use a strong, unique password and protect your devices.
        </p>
      </>
    ),
  },
  {
    id: "your-rights",
    title: "Your Rights and Choices",
    content: (
      <>
        <p>Depending on your location, you may have rights to:</p>
        <ul>
          <li>Access, correct, or delete personal information we hold about you;</li>
          <li>Export your data where the Service provides an export feature;</li>
          <li>Object to or restrict certain processing;</li>
          <li>Withdraw consent where processing is consent-based; and</li>
          <li>Lodge a complaint with a supervisory authority.</li>
        </ul>
        <p>
          You can update profile and privacy settings in the Service, manage subscription billing
          through Stripe Customer Portal where available, and contact us to exercise rights. We may
          verify your identity before responding.
        </p>
        <p>
          California residents may have additional rights under the CCPA/CPRA. EEA/UK users may have
          rights under GDPR. We aim to honor applicable legal requirements; during beta, response
          times may vary.
        </p>
      </>
    ),
  },
  {
    id: "children",
    title: "Age Requirement",
    content: (
      <p>
        You must be at least <strong>18 years old</strong> to use TradeTraxs. The Service is not
        directed to anyone under 18. We do not knowingly collect personal information from anyone
        under 18. If you believe someone under 18 has provided us information, contact us and we
        will take appropriate steps to delete it.
      </p>
    ),
  },
  {
    id: "international",
    title: "International Users",
    content: (
      <p>
        {LEGAL_ENTITY_NAME} operates TradeTraxs from the United States. If you access the Service
        from other regions, your information may be transferred to, stored, and processed in the
        United States and other countries where we or our providers operate, which may have different
        data protection laws than your home country.
      </p>
    ),
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    content: (
      <p>
        We may update this Privacy Policy from time to time. We will post the revised policy on this
        page and update the &quot;Last updated&quot; date. Material changes may be communicated
        through the Service or by email where appropriate. Continued use after changes become
        effective constitutes acceptance of the updated policy.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <>
        <p>
          For privacy questions, data requests, or concerns about this policy, contact us at:
        </p>
        <p>
          <strong>{LEGAL_ENTITY_NAME}</strong>
          <br />
          <strong>Email:</strong>{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>
        </p>
        <p>
          You may also use our{" "}
          <Link href="/support">Support</Link> page for account-related requests.
        </p>
      </>
    ),
  },
]
