import Link from "next/link"
import type { LegalSection } from "@/app/components/LegalDocumentLayout"
import { LEGAL_CONTACT_EMAIL, LEGAL_ENTITY_NAME } from "@/lib/legal/contact"
import { SITE_NAME, SITE_URL } from "@/lib/site"

export const TERMS_OF_SERVICE_SECTIONS: LegalSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    content: (
      <>
        <p>
          These Terms of Service (&quot;Terms&quot;) govern your access to and use of {SITE_NAME}{" "}
          (&quot;TradeTraxs,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) at{" "}
          <a href={SITE_URL}>{SITE_URL}</a>{" "}
          and related applications (the &quot;Service&quot;). {LEGAL_ENTITY_NAME} is the legal
          entity operating the Service.
        </p>
        <p>
          By creating an account, accessing, or using the Service, you agree to these Terms and our{" "}
          <Link href="/privacy">Privacy Policy</Link>. If you do not agree, do not use the Service.
        </p>
        <p>
          If you use the Service on behalf of an organization, you represent that you have authority
          to bind that organization, and &quot;you&quot; includes that organization.
        </p>
      </>
    ),
  },
  {
    id: "service-description",
    title: "Description of the Service",
    content: (
      <>
        <p>
          TradeTraxs is a <strong>trading journal and social community platform</strong> for
          educational, record-keeping, and community purposes. The Service allows you to log and
          import trades, analyze performance, share content with other users, participate in Trade
          Rooms, message other users, and access optional premium features such as AI Trade Analyst.
        </p>
        <p>
          <strong>TradeTraxs is not a broker, dealer, exchange, or investment adviser.</strong> We
          do not execute trades, hold customer funds for trading, or provide personalized investment
          advice. Nothing on the Service constitutes a recommendation to buy, sell, or hold any
          security or financial instrument.
        </p>
      </>
    ),
  },
  {
    id: "eligibility",
    title: "Eligibility",
    content: (
      <>
        <p>
          You must be at least <strong>18 years old</strong> to use TradeTraxs. You must be able to
          form a binding contract. You may not use the Service where prohibited by law.
        </p>
        <p>
          You are solely responsible for ensuring your use of the Service complies with applicable
          laws, broker rules, prop firm rules, and any agreements governing your trading activity.
        </p>
      </>
    ),
  },
  {
    id: "beta-program",
    title: "Beta Program",
    content: (
      <>
        <p>
          TradeTraxs is currently offered as a <strong>beta product</strong>.
        </p>
        <p>
          Features, functionality, pricing, analytics, AI outputs, integrations, and availability
          may change, be modified, or be removed at any time.
        </p>
        <p>
          You acknowledge that beta software may contain bugs, inaccuracies, interruptions, or
          unexpected behavior. You should independently verify any information generated by the
          platform before relying on it.
        </p>
      </>
    ),
  },
  {
    id: "accounts",
    title: "Account Responsibilities",
    content: (
      <>
        <p>When you register, you agree to:</p>
        <ul>
          <li>Provide accurate, current information and keep it updated;</li>
          <li>Maintain the security of your credentials and notify us of unauthorized access;</li>
          <li>Accept responsibility for activity under your account;</li>
          <li>Use one account per individual unless we authorize otherwise; and</li>
          <li>Not share, sell, or transfer your account without our consent.</li>
        </ul>
        <p>
          We may suspend or terminate accounts that violate these Terms, pose security risks, or harm
          other users or the Service.
        </p>
      </>
    ),
  },
  {
    id: "user-content",
    title: "User Content",
    content: (
      <>
        <p>
          &quot;User Content&quot; means content you submit to the Service, including trades,
          notes, images, videos, chart screenshots, reels, posts, comments, messages, room
          messages, profile information, and feedback.
        </p>
        <p>
          <strong>You retain ownership of your User Content.</strong> TradeTraxs does not claim
          ownership of material you upload.
        </p>
        <p>
          By uploading or submitting User Content, you represent and warrant that you{" "}
          <strong>own the content</strong> or <strong>have all necessary permission</strong> to
          upload, share, and display it on the Service.
        </p>
        <p>
          You are solely responsible for your User Content, including but not limited to:
        </p>
        <ul>
          <li>Images and chart screenshots;</li>
          <li>Videos and reels;</li>
          <li>Posts, comments, and messages; and</li>
          <li>Any other media or text you submit.</li>
        </ul>
        <p>
          By submitting User Content, you grant {LEGAL_ENTITY_NAME} a worldwide, non-exclusive,
          royalty-free license to host, store, reproduce, display, distribute, and adapt it solely
          to operate, improve, and promote the Service — including showing public content to other
          users as you direct through product features.
        </p>
        <p>You further represent that your User Content:</p>
        <ul>
          <li>Does not violate applicable law or third-party rights;</li>
          <li>Public trade claims you make are truthful to the best of your knowledge; and</li>
          <li>Does not include malware, spam, or deceptive content.</li>
        </ul>
        <p>
          {LEGAL_ENTITY_NAME} reserves the right to remove or restrict User Content that, in our
          reasonable judgment:
        </p>
        <ul>
          <li>Infringes copyright or other intellectual property rights;</li>
          <li>Infringes trademarks or other proprietary rights;</li>
          <li>Violates applicable law; or</li>
          <li>Violates these Terms or our{" "}
            <Link href="/community-guidelines">Community Guidelines</Link>.
          </li>
        </ul>
        <p>
          We may take these actions without prior notice in urgent cases. Copyright owners may
          report alleged infringement as described in our{" "}
          <Link href="/copyright">Copyright &amp; DMCA Policy</Link>.
        </p>
      </>
    ),
  },
  {
    id: "community-conduct",
    title: "Community Conduct",
    content: (
      <>
        <p>You agree not to:</p>
        <ul>
          <li>Harass, threaten, defame, or discriminate against others;</li>
          <li>Impersonate any person or misrepresent affiliations;</li>
          <li>Scrape, crawl, or reverse engineer the Service except as permitted by law;</li>
          <li>Circumvent security, rate limits, or access controls;</li>
          <li>Use the Service for unlawful gambling promotion, pump-and-dump schemes, or fraud;</li>
          <li>Upload others&apos; personal data without permission; or</li>
          <li>Interfere with the Service&apos;s operation or other users&apos; experience.</li>
        </ul>
        <p>
          Trade Rooms, messaging, and public feeds are community spaces. Room owners and admins may
          have additional moderation tools where available; we may enforce these Terms where we have
          reasonable ability to do so, but we do not guarantee continuous or comprehensive
          moderation during beta.
        </p>
      </>
    ),
  },
  {
    id: "subscriptions",
    title: "Subscriptions and TraxPro",
    content: (
      <>
        <p>
          TradeTraxs offers free and paid subscription tiers (e.g., TraxPro). Feature availability
          may differ by plan and may change over time with reasonable notice where required.
        </p>
        <p>
          Paid subscriptions are billed through <strong>Stripe</strong>. By subscribing, you
          authorize recurring charges according to the plan you select. Free trials or promotional
          pricing, if offered, will be described at checkout.
        </p>
        <p>
          Subscription management, including payment method updates, may be available through Stripe
          Customer Portal or account settings as provided in the Service.
        </p>
      </>
    ),
  },
  {
    id: "payment-terms",
    title: "Payment Terms",
    content: (
      <>
        <p>
          All fees are stated in U.S. dollars unless otherwise indicated. Taxes may apply based on
          your location and will be added where required.
        </p>
        <p>
          You agree to provide valid payment information and promptly update it. Failed payments may
          result in suspension of paid features. Chargebacks or payment disputes made in bad faith
          may lead to account termination.
        </p>
        <p>
          Except where required by law, subscription fees are non-refundable once a billing period
          has begun. Contact{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a> for billing
          questions.
        </p>
      </>
    ),
  },
  {
    id: "cancellation",
    title: "Cancellation Policy",
    content: (
      <>
        <p>
          You may cancel a subscription at any time through the Stripe Customer Portal or other
          cancellation method provided in the Service. Cancellation stops future renewals; you
          typically retain paid features until the end of the current billing period unless
          otherwise stated at checkout.
        </p>
        <p>
          We may change subscription prices or features with notice as required by law or your
          agreement with Stripe. Continued use after a price change constitutes acceptance where
          permitted.
        </p>
        <p>
          Deleting your TradeTraxs account is separate from canceling billing. Cancel your
          subscription before deleting your account if you wish to avoid further charges.
        </p>
      </>
    ),
  },
  {
    id: "affiliate-program",
    title: "Affiliate and Referral Program",
    content: (
      <>
        <p>
          TradeTraxs may offer referral or affiliate programs that allow eligible users to earn
          commissions for qualified referrals. Participation requires approval and is subject to
          separate program rules presented in the Service.
        </p>
        <p>If you participate, you agree to:</p>
        <ul>
          <li>Disclose affiliate relationships where required by law (including FTC guidelines);</li>
          <li>Not use spam, misleading claims, or prohibited bidding on our trademarks;</li>
          <li>Provide accurate tax and payout information for Stripe Connect or other payout methods;</li>
          <li>Accept that commissions, payout thresholds, and eligibility are determined by us and may change; and</li>
          <li>Accept that fraudulent referrals may result in forfeiture of earnings and termination.</li>
        </ul>
        <p>
          Affiliate payouts are processed according to program terms and applicable tax laws. We are
          not responsible for third-party payout delays outside our control.
        </p>
      </>
    ),
  },
  {
    id: "ai-analyst",
    title: "AI Trade Analyst Disclaimer",
    content: (
      <>
        <p>
          The AI Trade Analyst and related features use automated systems, including third-party AI
          models, to generate commentary based on trade data and prompts you provide.
        </p>
        <p>
          <strong>AI output is for informational and educational purposes only — not financial
          advice.</strong> AI Trade Analyst output may be inaccurate, incomplete, delayed, or
          incorrect. Responses may take time to generate or fail to generate. You must independently
          verify any information before relying on it.
        </p>
        <p>
          AI features are not a substitute for professional financial, investment, tax, or legal
          advice. You remain fully responsible for all trading decisions, including any decisions
          influenced by AI-generated content. {LEGAL_ENTITY_NAME} is not liable for trading losses
          or other damages resulting from reliance on AI-generated content, subject to the
          Limitation of Liability section below.
        </p>
        <p>
          Do not submit confidential broker credentials or sensitive personal data you do not want
          processed by AI providers.
        </p>
      </>
    ),
  },
  {
    id: "no-financial-advice",
    title: "No Financial Advice",
    content: (
      <>
        <p>
          <strong>
            TradeTraxs does not provide investment advice, trading recommendations, or suitability
            analysis.
          </strong>{" "}
          Content on the Service — including user posts, leaderboard rankings, shared trades, room
          discussions, and AI-generated text — reflects opinions or records of users or automated
          systems, not recommendations from {LEGAL_ENTITY_NAME}.
        </p>
        <p>
          <strong>Trading involves substantial risk of loss.</strong> Past performance displayed in
          journals, leaderboards, or shared trades does not guarantee future results. You are
          solely responsible for your trades, decisions, profits, losses, and financial outcomes,
          and for your compliance with applicable regulations.
        </p>
      </>
    ),
  },
  {
    id: "csv-imports",
    title: "CSV Imports and Third-Party Data",
    content: (
      <>
        <p>
          You may import trade data from CSV files exported from other platforms. You represent that
          you have the right to import that data and that it is accurate to the best of your
          knowledge.
        </p>
        <p>
          Import parsers may not support every broker format. We do not guarantee error-free
          imports. Review imported trades before relying on analytics or sharing them publicly.
        </p>
      </>
    ),
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: (
      <>
        <p>
          The Service, including software, design, logos, and documentation (excluding User Content),
          is owned by {LEGAL_ENTITY_NAME} or its licensors and protected by intellectual property
          laws. You receive a limited, non-exclusive, non-transferable license to use the Service for
          personal or internal business journaling and community participation according to these
          Terms.
        </p>
        <p>
          You may not copy, modify, distribute, or create derivative works of the Service except as
          permitted by law or with our written consent.
        </p>
      </>
    ),
  },
  {
    id: "third-party-services",
    title: "Third-Party Services",
    content: (
      <>
        <p>
          The Service integrates with third parties such as Supabase, Stripe, Google sign-in,
          Vercel, and AI providers. Your use of those services may be subject to their terms. We are
          not responsible for third-party services outside our reasonable control.
        </p>
        <p>
          Links to external sites do not imply endorsement. Use external sites at your own risk.
        </p>
      </>
    ),
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    content: (
      <>
        <p>
          THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES
          OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF
          MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
        </p>
        <p>
          WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR THAT DATA
          WILL BE PRESERVED WITHOUT LOSS. AS DESCRIBED IN THE BETA PROGRAM SECTION, FEATURES MAY
          CHANGE OR BE WITHDRAWN WITHOUT NOTICE.
        </p>
      </>
    ),
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    content: (
      <>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, {LEGAL_ENTITY_NAME.toUpperCase()} AND ITS OFFICERS,
          DIRECTORS, EMPLOYEES, AND SUPPLIERS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
          SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA,
          GOODWILL, OR TRADING LOSSES (INCLUDING LOSSES ARISING FROM AI-GENERATED CONTENT), ARISING
          FROM OR RELATED TO THE SERVICE OR THESE TERMS, EVEN IF ADVISED OF THE POSSIBILITY.
        </p>
        <p>
          OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THE SERVICE OR THESE TERMS
          WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS BEFORE
          THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS (US $100).
        </p>
        <p>
          SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS; IN THOSE CASES, OUR LIABILITY IS
          LIMITED TO THE FULLEST EXTENT PERMITTED BY LAW.
        </p>
      </>
    ),
  },
  {
    id: "indemnification",
    title: "Indemnification",
    content: (
      <p>
        You agree to indemnify and hold harmless {LEGAL_ENTITY_NAME}{" "}
        and its affiliates from claims, damages, losses, and expenses (including reasonable
        attorneys&apos; fees) arising from your User Content, your use of the Service, your
        violation of these Terms, or your violation of any rights of another person or entity.
      </p>
    ),
  },
  {
    id: "termination",
    title: "Account Termination",
    content: (
      <>
        <p>
          You may stop using the Service at any time and may delete your account where the feature
          is available. We may suspend or terminate your access immediately if you breach these Terms,
          create risk or legal exposure, or if we discontinue the Service.
        </p>
        <p>
          Upon termination, your right to use the Service ceases. Provisions that by nature should
          survive (including disclaimers, limitation of liability, indemnification, and governing law)
          will survive termination.
        </p>
      </>
    ),
  },
  {
    id: "governing-law",
    title: "Governing Law and Disputes",
    content: (
      <>
        <p>
          These Terms are governed by the laws of the State of Florida, United States, without regard
          to conflict of law principles, except where mandatory consumer protection laws of your
          jurisdiction apply.
        </p>
        <p>
          Any dispute arising from these Terms or the Service will be resolved in the state or
          federal courts located in Florida, and you consent to personal jurisdiction there, unless
          applicable law requires otherwise.
        </p>
        <p>
          Before filing a formal claim, you agree to contact us at{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a> and attempt to resolve
          the dispute informally within thirty (30) days.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to These Terms",
    content: (
      <p>
        We may modify these Terms at any time. We will post updated Terms on this page and revise
        the &quot;Last updated&quot; date. Material changes may be notified through the Service or
        by email. Continued use after changes take effect constitutes acceptance. If you do not agree,
        you must stop using the Service.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact Information",
    content: (
      <>
        <p>For questions about these Terms, contact:</p>
        <p>
          <strong>{LEGAL_ENTITY_NAME}</strong>
          <br />
          <strong>Email:</strong>{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`}>{LEGAL_CONTACT_EMAIL}</a>
        </p>
        <p>
          Support requests: <Link href="/support">Contact Support</Link>
        </p>
      </>
    ),
  },
]
