import type { Achievement } from "@/lib/achievementTypes"
import { ACHIEVEMENT_TYPE } from "@/lib/achievementTypes"
import { DEMO_USER_ID } from "./constants"
import { demoStaticImageUrl } from "./demoAssets"
import { isoDemoDaysAgo } from "./demoTime"
const DEMO_ACHIEVEMENT_RECORDS: Achievement[] = [
  {
    id: "demo-ach-1",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.PROP_FIRM_PAYOUT,
    title: "First Prop Firm Payout",
    description: "Apex 150K funded account. First withdrawal",
    badge_key: "prop_payout",
    tier: "gold",
    category: "prop_firm_payouts",
    value_numeric: 2400,
    value_text: null,
    currency: "USD",
    account_type: "Prop Firm",
    account_name: "Apex 150K Funded",
    account_size: "150000",
    mode: "funded",
    firm: "Apex",
    image_url: demoStaticImageUrl("demo-ach-1"),
    achieved_at: isoDemoDaysAgo(45, 10),
    created_at: isoDemoDaysAgo(45, 10),
    updated_at: isoDemoDaysAgo(45, 10),
    is_featured: true,
    is_public: true,
    sort_order: 1,
    metadata: null,
  },
  {
    id: "demo-ach-2",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.PASSED_EVAL,
    title: "Prop Firm Passed",
    description: "Apex 150K evaluation cleared",
    badge_key: "prop_pass",
    tier: "platinum",
    category: "passed_evals",
    value_numeric: 150000,
    value_text: "150K",
    currency: "USD",
    account_type: "Prop Firm",
    account_name: "Apex 150K Eval",
    account_size: "150000",
    mode: "eval",
    firm: "Apex",
    image_url: demoStaticImageUrl("demo-ach-2"),
    created_at: isoDemoDaysAgo(60, 9),
    updated_at: isoDemoDaysAgo(60, 9),
    is_featured: true,
    is_public: true,
    sort_order: 2,
    metadata: null,
  },
  {
    id: "demo-ach-3",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.MILESTONE,
    title: "100 Trades Logged",
    description: "Consistency builds edge",
    badge_key: "trades_100",
    tier: "silver",
    category: "milestones",
    value_numeric: 100,
    value_text: "100",
    currency: null,
    account_type: null,
    account_name: null,
    account_size: null,
    mode: null,
    firm: null,
    image_url: demoStaticImageUrl("demo-ach-3"),
    created_at: isoDemoDaysAgo(90, 11),
    updated_at: isoDemoDaysAgo(90, 11),
    is_featured: false,
    is_public: true,
    sort_order: 3,
    metadata: null,
  },
  {
    id: "demo-ach-4",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.MILESTONE,
    title: "First Green Week",
    description: "5 consecutive profitable days",
    badge_key: "green_week",
    tier: "bronze",
    category: "milestones",
    value_numeric: 5,
    value_text: "5 days",
    currency: null,
    account_type: null,
    account_name: null,
    account_size: null,
    mode: null,
    firm: null,
    image_url: demoStaticImageUrl("demo-ach-4"),
    created_at: isoDemoDaysAgo(20, 16),
    updated_at: isoDemoDaysAgo(20, 16),
    is_featured: false,
    is_public: true,
    sort_order: 4,
    metadata: null,
  },
  {
    id: "demo-ach-5",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.MILESTONE,
    title: "Clip Creator",
    description: "10 trade breakdown clips published",
    badge_key: "reel_creator",
    tier: "gold",
    category: "milestones",
    value_numeric: 10,
    value_text: "10 clips",
    currency: null,
    account_type: null,
    account_name: null,
    account_size: null,
    mode: null,
    firm: null,
    image_url: demoStaticImageUrl("demo-ach-5"),
    created_at: isoDemoDaysAgo(75, 14),
    updated_at: isoDemoDaysAgo(75, 14),
    is_featured: false,
    is_public: true,
    sort_order: 5,
    metadata: null,
  },
  {
    id: "demo-ach-6",
    user_id: DEMO_USER_ID,
    achievement_type: ACHIEVEMENT_TYPE.MILESTONE,
    title: "Risk Discipline",
    description: "30 days within daily loss limit",
    badge_key: "risk_discipline",
    tier: "silver",
    category: "milestones",
    value_numeric: 30,
    value_text: "30 days",
    currency: null,
    account_type: null,
    account_name: null,
    account_size: null,
    mode: null,
    firm: null,
    image_url: demoStaticImageUrl("demo-ach-6"),
    created_at: isoDemoDaysAgo(120, 10),
    updated_at: isoDemoDaysAgo(120, 10),
    is_featured: false,
    is_public: true,
    sort_order: 6,
    metadata: null,
  },
]

export function isDemoAchievementUserId(userId: string): boolean {
  return userId === DEMO_USER_ID
}

export function getDemoAchievementsForUser(userId: string): Achievement[] {
  if (!isDemoAchievementUserId(userId)) return []
  return DEMO_ACHIEVEMENT_RECORDS
}

export function getDemoPublicAchievementsForUser(userId: string): Achievement[] {
  return getDemoAchievementsForUser(userId).filter((a) => a.is_public)
}
