import type { GettingStartedChecklistSignals } from "./gettingStartedChecklistSignals.types.ts"

export type GettingStartedSignalsFixture = {
  wire: Record<string, unknown>
  expected: GettingStartedChecklistSignals
}

const NEW_USER: GettingStartedChecklistSignals = {
  onboardingCompleted: false,
  hasSeenGettingStartedIntro: false,
  hasSeenOnboardingCompletePopup: false,
  tradeCount: 0,
  profilePostCount: 0,
  followCount: 0,
  hasEverJoinedOtherRoom: false,
  hasPublicTrade: false,
  firstPrivateTradeId: null,
}

export const gettingStartedContractFixtures: Record<
  string,
  GettingStartedSignalsFixture
> = {
  newUser: {
    wire: {
      onboarding_completed: false,
      has_seen_getting_started_intro: false,
      has_seen_onboarding_complete_popup: false,
      trade_count: 0,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: NEW_USER,
  },
  onboardingCompleted: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: false,
      trade_count: 0,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: {
      ...NEW_USER,
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
    },
  },
  hasAnyTrade: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 2,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: "11111111-1111-1111-1111-111111111111",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 2,
      profilePostCount: 0,
      followCount: 0,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: false,
      firstPrivateTradeId: "11111111-1111-1111-1111-111111111111",
    },
  },
  hasPublicTrade: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 3,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: true,
      first_private_trade_id: "22222222-2222-2222-2222-222222222222",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 3,
      profilePostCount: 0,
      followCount: 0,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: true,
      firstPrivateTradeId: "22222222-2222-2222-2222-222222222222",
    },
  },
  hasQualifyingPrivateTrade: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 1,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: "33333333-3333-3333-3333-333333333333",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 1,
      profilePostCount: 0,
      followCount: 0,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: false,
      firstPrivateTradeId: "33333333-3333-3333-3333-333333333333",
    },
  },
  hasProfilePost: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 1,
      profile_post_count: 1,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 1,
      profilePostCount: 1,
      followCount: 0,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: false,
      firstPrivateTradeId: null,
    },
  },
  followsAnotherUser: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 0,
      profile_post_count: 0,
      follow_count: 2,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 0,
      profilePostCount: 0,
      followCount: 2,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: false,
      firstPrivateTradeId: null,
    },
  },
  ownsOrBelongsToRoom: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 0,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: true,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 0,
      profilePostCount: 0,
      followCount: 0,
      hasEverJoinedOtherRoom: true,
      hasPublicTrade: false,
      firstPrivateTradeId: null,
    },
  },
  noMatchingRows: {
    wire: {
      onboarding_completed: false,
      has_seen_getting_started_intro: false,
      has_seen_onboarding_complete_popup: false,
      trade_count: 0,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: null,
    },
    expected: NEW_USER,
  },
  freeUser: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: false,
      trade_count: 1,
      profile_post_count: 0,
      follow_count: 0,
      has_ever_joined_other_room: false,
      has_public_trade: false,
      first_private_trade_id: "44444444-4444-4444-4444-444444444444",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: false,
      tradeCount: 1,
      profilePostCount: 0,
      followCount: 0,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: false,
      firstPrivateTradeId: "44444444-4444-4444-4444-444444444444",
    },
  },
  trialUser: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 5,
      profile_post_count: 1,
      follow_count: 1,
      has_ever_joined_other_room: false,
      has_public_trade: true,
      first_private_trade_id: "55555555-5555-5555-5555-555555555555",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 5,
      profilePostCount: 1,
      followCount: 1,
      hasEverJoinedOtherRoom: false,
      hasPublicTrade: true,
      firstPrivateTradeId: "55555555-5555-5555-5555-555555555555",
    },
  },
  proUser: {
    wire: {
      onboarding_completed: true,
      has_seen_getting_started_intro: true,
      has_seen_onboarding_complete_popup: true,
      trade_count: 12,
      profile_post_count: 3,
      follow_count: 4,
      has_ever_joined_other_room: true,
      has_public_trade: true,
      first_private_trade_id: "66666666-6666-6666-6666-666666666666",
    },
    expected: {
      onboardingCompleted: true,
      hasSeenGettingStartedIntro: true,
      hasSeenOnboardingCompletePopup: true,
      tradeCount: 12,
      profilePostCount: 3,
      followCount: 4,
      hasEverJoinedOtherRoom: true,
      hasPublicTrade: true,
      firstPrivateTradeId: "66666666-6666-6666-6666-666666666666",
    },
  },
}
