-- Column REVOKE does not override an existing table-level SELECT grant.
-- Replace profiles SELECT with an explicit public-column grant. The nine
-- internal columns stay readable through profile_owner_private_fields()
-- and service_role.

revoke select on table public.profiles from anon, authenticated;

grant select (
  id,
  name,
  username,
  created_at,
  bio,
  avatar_url,
  is_private,
  trading_style,
  experience,
  is_pro,
  subscription_status,
  referred_by,
  referral_count,
  started_trading,
  trading_model,
  max_drawdown_limit,
  referral_code,
  is_banned,
  banned_reason,
  banned_at,
  banned_by,
  onboarding_completed,
  has_used_csv_import,
  trial_end,
  current_period_end,
  cancel_at_period_end,
  has_used_initial_import,
  primary_market,
  username_change_count,
  trader_type,
  is_beta_tester,
  has_seen_getting_started_intro,
  has_seen_onboarding_complete_popup,
  beta_signup_notified_at,
  cancel_at,
  has_email_password,
  use_free_tier,
  last_csv_import_at,
  creator_access,
  creator_code,
  creator_granted_at,
  early_access_enrolled_at,
  early_access_started_at,
  early_access_ends_at,
  early_access_status,
  early_access_campaign_id,
  early_access_enrollment_source,
  signup_flow_source,
  lifetime_access_source,
  lifetime_access_granted_at,
  dm_privacy,
  tradovate_login_import_reminder_opt_out
) on table public.profiles to anon, authenticated;
